### PR TITLE
Fix types

### PR DESCRIPTION
**Pull request by SiriOvregard**
Added method for fetching correct types for data

### CODE REVIEW

**Comment by rafaelschlatter** [comment]
I dont see the full test results because I dont have access to the Azure DevOps project anymore, but I assume 11/12 test failures are caused by "No mock address".

This is because whenever `requests_mock` is used in a test, one has to provide a mock for all api requests made in the test. The three `getDataBy...()` methods now make a call to the types api (through `_getData()` and `getTypes()`), and it is now complaining about not finding these mock addresses.

This can be fixed by adding this piece of code to all tests testing a `getDataBy...()` function:
````
requests_mock.request(
    "GET",
    MockURLs.types_url,
    json=MockResponses.mock_types
)
````

Some tests also require a mock for the call to the instances api. This can be added in a similar way.

You might need to edit the mock responses as well, depending on the use. You can find the mock responses in `tests/mock_responses.py` in the `MockResponses` class. See whether `mock_types` and `mock_instances` contain all the info you need. So far I just copied a basic example from the Azure documentation, but this might not be sophisticated enough.

Let me know if you need help on this.

Cheers, Rafael

**Comment by srudaa** [comment]
Cheers @rafaelschlatter.  @SiriOvregard  can you implement and send new PR.

**Comment by SiriOvregard** [comment]
Thanks @rafaelschlatter! You are right, tests fails with "NoMockAddress" presumably because I changed the output type of getTypes(). I will look into it :)

**Comment by rafaelschlatter** [comment]
> Thanks @rafaelschlatter! You are right, tests fails with "NoMockAddress" presumably because I changed the output type of getTypes(). I will look into it :)

The changed output of `getTypes()` is only causing one test to fail I think.

All the ones with "NoMockAddress" fail because some api calls are not mocked in the tests. Try adding the above code snippet to the tests that complain about missing a mock address. You will find a lot of examples in the tests already. Depending on whether it complains about instances or types, you need to add them accordingly (maybe both :)). You need to fake all api calls made in a test.

You can run tests locally with `python -m pytest -v`, so you see whether the tests fail or pass before pushing a commit.

**Comment by srudaa** [comment]
Great work @SiriOvregard. Thank you @rafaelschlatter for guidance!

**Comment by SiriOvregard** [comment]
@rafaelschlatter @srudaa Thanks guys! :)

Yes, I had to match a type id in the mock query response with a type id in the mock type response due to the new structure for identifying type in the code. Great if there are additional advantages :) And thank you for guidance Rafael, it was really helpful!

**Pull request merged**
